# Generated by Django 2.2.17 on 2020-11-11 16:08

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypage',
            name='pages',
            field=wagtail.core.fields.StreamField([('page', wagtail.core.blocks.StructBlock([('id', wagtail.core.blocks.CharBlock()), ('html', wagtail.core.blocks.RawHTMLBlock())]))], default=''),
            preserve_default=False,
        ),
    ]
