# Generated by Django 2.2.17 on 2020-11-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_storypage_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypage',
            name='custom_css',
            field=models.TextField(blank=True),
        ),
    ]
