# Generated by Django 2.2.17 on 2020-11-18 17:01

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_webstories.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_blogpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('story_embed', wagtail_webstories.blocks.StoryEmbedBlock())]),
        ),
    ]
