# Generated by Django 2.2.17 on 2020-11-19 12:28

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_webstories.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('stories', '0006_add_story_embed_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('story_embed', wagtail_webstories.blocks.StoryEmbedBlock()), ('carousel', wagtail.core.blocks.StreamBlock([('story', wagtail_webstories.blocks.StoryChooserBlock())], template='stories/blocks/carousel.html'))]),
        ),
    ]
